
name: github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm ci

      - name: Build production website
        run: npm run build:ci
      
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      # - name: Deploy to GitHub Pages
      #   run: ngh --dir dist/sample

  # copy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Copycat
  #     uses: andstor/copycat-action@v3
  #     with:
  #       personal_token: ${{ secrets.GH_PAGES }}
  #       src_path: dist/sample/index.html
  #       dst_path: dist/sample/404.html
  #       dst_owner: amitpnk
  #       dst_repo_name: angular-pages
  #       dst_branch: gh-pages
  #       src_branch: gh-pages
  copy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES }}
          BRANCH: gh-pages
          source: "index.html"
          target: "404.html"

  deploy:
    runs-on: ubuntu-latest
    needs: copy
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/sample
